# Generated by Django 6.0.6 on 2026-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_personaldocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='e_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
