# Generated by Django 6.0.6 on 2026-06-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_users_e_reg_no_users_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR Manager', 'HR Manager'), ('Recruiter', 'Recruiter'), ('Employee', 'Employee'), ('Crew', 'Crew')], default='Employee', max_length=20),
        ),
    ]
